-- Reset Table
drop table if exists public.messages cascade;

-- Create a table for public feedback
create table
  public.messages (
    id bigint generated by default as identity primary key,
    state text not null,
    plate_number text not null,
    message text,
    display_name text,
	created_at timestamp with time zone default (now() at time zone 'utc') not null,
    active boolean default true not null,
	flags int default 0,

	constraint message_length check (char_length(message) >= 5),
	constraint name_length check (char_length(display_name) >= 2)
  );

-- Set up Row Level Security (RLS)
alter table public.messages enable row level security;

create policy "messages viewable by everyone." on public.messages for
select
  using (true);

create policy "Anyone can insert messages." on public.messages for insert
with
  check (true);

create policy "Messages updatable by anyone." on public.messages
for update
  using (true);